apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend-api
resources:
- frontend-cm.yaml
- frontend-depl.yaml
- frontend-secret.yaml
- frontend-svc.yaml
- ingress.yaml
- frontend-ns.yaml
