apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-cm.yaml
  - frontend-depl.yaml
  - frontend-secret.yaml
  - frontend-svc.yaml
  - ingress.yaml
  - ./db/postgres-cm.yaml
  - ./db/postgres-headless-svc.yaml
  - ./db/postgres-secret.yaml
  - ./db/postgres-sts.yaml
  - ./db/postgres-svc.yaml
  - ./db/pv.yaml
  - ./db/pvc.yaml