apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-cm.yaml
  - frontend-depl.yaml
  - frontend-secret.yaml
  - frontend-svc.yaml
  - ingress.yaml
  - postgres-cm.yaml
  - postgres-headless-svc.yaml
  - postgres-secret.yaml
  - postgres-sts.yaml
  - postgres-svc.yaml
  - pv.yaml
  - pvc.yaml