apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-ingress
  namespace: frontend-api
spec:
  rules:
  - host: "app.santoshdts"
    http:
      paths:
      - pathType: Prefix
        path: "/books"
        backend:
          service:
            name: frontend-svc
            port:
              number: 8080
