kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: database
  name: bookstore-pv-claim  
  labels:
    app: bookstore
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi  
