resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

replicas: 1

frontendEnv:
  cmName: frontend-cm
  secretName: frontend-secret

backendEnv:
  secretName: postgres-secret
  cmName: postgres-config

frontendCM:
  dbHost: postgres-0.postgres.database.svc.cluster.local:5432 


storage:
  capacity: 1Gi

