apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-cm.yaml
  - postgres-headless-svc.yaml
  - postgres-secret.yaml
  - postgres-sts.yaml
  - postgres-svc.yaml
  - pv.yaml
  - pvc.yaml