name: GHCR Build and Push

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'release/*'

jobs:
  ghcr:
    env:
      REGISTRY: ghcr.io
      IMAGE: santosh1176/bookstore
      COMMIT_SHA: ${{github.sha}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: fluxcd/flux2/action@main
      - uses: actions/checkout@v3
      - name: Set environment variable
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
      - name: Prepare
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TS=$(date +%s)
          REVISION=${GITHUB_SHA::8}
          BUILD_ID="${REVISION}-${TS}"
          LATEST_ID=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\//}
          fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=BUILD_ID::${BUILD_ID}
          echo ::set-output name=LATEST_ID::${LATEST_ID}          

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Set commit SHA
        id: set_commit_sha
        run: echo "::set-output name=COMMIT_SHA::$(git rev-parse --short HEAD)"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_ID }}
      
      - name: Publish Flux OCI artifact to GHCR
        id: Push_Artifact
        run: |
          flux push artifact oci://ghcr.io/santosh1176/manifests/bookstore:${{ steps.prep.outputs.VERSION }} \
            --path="./kustomize" \
            --source="${{ github.event.repository.html_url }}" \
            --revision="${GITHUB_REF_NAME}/${GITHUB_SHA}"
          flux tag artifact oci://ghcr.io/santosh1176/manifests/bookstore:${{ steps.prep.outputs.VERSION }} --tag latest
      
      
      - name: Image digest
        run: echo ${{COMMIT_SHA}}
